### ISSUE TITLE
Ignore node_modules by default

### ISSUE THREAD

**Issue by MoOx** [DSchau/prettier-markdown#6]
If I want to use `prettier-markdown "packages/**/*.md"` I just can't since it's the cli is not ignoring node_modules by default (in practise I should probably be able to, but a module I use have a malformed js snippet in its readme).

**Comment by DSchau** [comment]
Good call! I will be relatively busy until later this week, but I'll try and get that built in.

PRs also welcome and encouraged 😄

**Comment by DSchau** [comment]
But also meant to mention, thanks for using the tool and thanks for the feedback! Glad you seem to be getting some usage out of it :)

**Comment by DSchau** [comment]
@MoOx fixed; I will release this in a bit!

**Comment by MoOx** [comment]
Thanks!
